<?xml version="1.0" encoding="utf-8"?><Database Name="CarShowDB" Class="CarShowRoomDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\CarShowDB.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="WindowsFormsApplication1.Properties.Settings" SettingsPropertyName="CarShowDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LogIn" Member="LogIns">
    <Type Name="LogIn">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Emp" Member="Emps">
    <Type Name="Emp">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="L_Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="JoinDate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateofBirth" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Salary" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="JobType" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BankPolicy" Member="BankPolicies">
    <Type Name="BankPolicy">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Branch" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Branch" Member="Branches">
    <Type Name="Branch">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BranchName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Car" Member="Cars">
    <Type Name="Car">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DealerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EngineNo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Car_Customer" Member="Customers" ThisKey="Id" OtherKey="CarId" Type="Customer" />
      <Association Name="Dealer_Car" Member="Dealer" ThisKey="DealerId" OtherKey="Id" Type="Dealer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="L_Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CarId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Buying_Date" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Car_Customer" Member="Car" ThisKey="CarId" OtherKey="Id" Type="Car" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Dealer" Member="Dealers">
    <Type Name="Dealer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="L_Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Dealer_Car" Member="Cars" ThisKey="Id" OtherKey="DealerId" Type="Car" />
    </Type>
  </Table>
</Database>